### ISSUE TITLE
index.yaml中url格式不合理

### ISSUE THREAD

**Issue by niusmallnan** [cloudnativeapp/charts#16]
这是apphub的格式：
```
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: apache
    sources:
    - https://github.com/bitnami/bitnami-docker-apache
    urls:
    - charts/apache-4.3.2.tgz # here 
    version: 4.3.2
```

这是官方helm的格式：
```

apiVersion: v1
entries:
  nginx:
    - urls:
        - https://kubernetes-charts.storage.googleapis.com/nginx-0.1.0.tgz # here
      name: nginx
      description: string
      version: 0.1.0
      home: https://github.com/something
      digest: "sha256:1234567890abcdef"
```
按照URL的语义应该在`charts/apache-4.3.2.tgz`前补充完整，比如：
`https://apphub.aliyuncs.com/charts/apache-4.3.2.tgz`
